return {
    width = 4,
    height = 4,
    grid = {
        [0] = { visited = true, room = true },
        [1] = { visited = true, room = true },
        [2] = { visited = true, room = true },
        [3] = { visited = true, room = true },
        [4] = { visited = true, room = true },
        [5] = { visited = true, room = true },
        [6] = { visited = true, room = true },
        [7] = { visited = true, room = true },
        [8] = { visited = true, room = true },
        [9] = { visited = true, room = true },
        [10] = { visited = true, room = true },
        [11] = { visited = true, room = true },
        [12] = { visited = true, room = true },
        [13] = { visited = true, room = true },
        [14] = { visited = true, room = true },
        [15] = { visited = true, room = true },
    },
    start = { x = 1, y = 1 },
    adjacency = {
        [0] = {
            [0] = true,
            [1] = true,
            [2] = false,
            [3] = false,
            [4] = true,
            [5] = false,
            [6] = false,
            [7] = false,
            [8] = false,
            [9] = false,
            [10] = false,
            [11] = false,
            [12] = false,
            [13] = false,
            [14] = false,
            [15] = false,
        },
        [1] = {
            [0] = true,
            [1] = true,
            [2] = true,
            [3] = false,
            [4] = false,
            [5] = true,
            [6] = false,
            [7] = false,
            [8] = false,
            [9] = false,
            [10] = false,
            [11] = false,
            [12] = false,
            [13] = false,
            [14] = false,
            [15] = false,
        },
        [2] = {
            [0] = false,
            [1] = true,
            [2] = true,
            [3] = true,
            [4] = false,
            [5] = false,
            [6] = true,
            [7] = false,
            [8] = false,
            [9] = false,
            [10] = false,
            [11] = false,
            [12] = false,
            [13] = false,
            [14] = false,
            [15] = false,
        },
        [3] = {
            [0] = false,
            [1] = false,
            [2] = true,
            [3] = true,
            [4] = false,
            [5] = false,
            [6] = false,
            [7] = true,
            [8] = false,
            [9] = false,
            [10] = false,
            [11] = false,
            [12] = false,
            [13] = false,
            [14] = false,
            [15] = false,
        },
        [4] = {
            [0] = true,
            [1] = false,
            [2] = false,
            [3] = false,
            [4] = true,
            [5] = true,
            [6] = false,
            [7] = false,
            [8] = true,
            [9] = false,
            [10] = false,
            [11] = false,
            [12] = false,
            [13] = false,
            [14] = false,
            [15] = false,
        },
        [5] = {
            [0] = false,
            [1] = true,
            [2] = false,
            [3] = false,
            [4] = true,
            [5] = true,
            [6] = true,
            [7] = false,
            [8] = false,
            [9] = true,
            [10] = false,
            [11] = false,
            [12] = false,
            [13] = false,
            [14] = false,
            [15] = false,
        },
        [6] = {
            [0] = false,
            [1] = false,
            [2] = true,
            [3] = false,
            [4] = false,
            [5] = true,
            [6] = true,
            [7] = true,
            [8] = false,
            [9] = false,
            [10] = true,
            [11] = false,
            [12] = false,
            [13] = false,
            [14] = false,
            [15] = false,
        },
        [7] = {
            [0] = false,
            [1] = false,
            [2] = false,
            [3] = true,
            [4] = false,
            [5] = false,
            [6] = true,
            [7] = true,
            [8] = false,
            [9] = false,
            [10] = false,
            [11] = true,
            [12] = false,
            [13] = false,
            [14] = false,
            [15] = false,
        },
        [8] = {
            [0] = false,
            [1] = false,
            [2] = false,
            [3] = false,
            [4] = true,
            [5] = false,
            [6] = false,
            [7] = false,
            [8] = true,
            [9] = true,
            [10] = false,
            [11] = false,
            [12] = true,
            [13] = false,
            [14] = false,
            [15] = false,
        },
        [9] = {
            [0] = false,
            [1] = false,
            [2] = false,
            [3] = false,
            [4] = false,
            [5] = true,
            [6] = false,
            [7] = false,
            [8] = true,
            [9] = true,
            [10] = true,
            [11] = false,
            [12] = false,
            [13] = true,
            [14] = false,
            [15] = false,
        },
        [10] = {
            [0] = false,
            [1] = false,
            [2] = false,
            [3] = false,
            [4] = false,
            [5] = false,
            [6] = true,
            [7] = false,
            [8] = false,
            [9] = true,
            [10] = true,
            [11] = true,
            [12] = false,
            [13] = false,
            [14] = true,
            [15] = false,
        },
        [11] = {
            [0] = false,
            [1] = false,
            [2] = false,
            [3] = false,
            [4] = false,
            [5] = false,
            [6] = false,
            [7] = true,
            [8] = false,
            [9] = false,
            [10] = true,
            [11] = true,
            [12] = false,
            [13] = false,
            [14] = false,
            [15] = true,
        },
        [12] = {
            [0] = false,
            [1] = false,
            [2] = false,
            [3] = false,
            [4] = false,
            [5] = false,
            [6] = false,
            [7] = false,
            [8] = true,
            [9] = false,
            [10] = false,
            [11] = false,
            [12] = true,
            [13] = true,
            [14] = false,
            [15] = false,
        },
        [13] = {
            [0] = false,
            [1] = false,
            [2] = false,
            [3] = false,
            [4] = false,
            [5] = false,
            [6] = false,
            [7] = false,
            [8] = false,
            [9] = true,
            [10] = false,
            [11] = false,
            [12] = true,
            [13] = true,
            [14] = true,
            [15] = false,
        },
        [14] = {
            [0] = false,
            [1] = false,
            [2] = false,
            [3] = false,
            [4] = false,
            [5] = false,
            [6] = false,
            [7] = false,
            [8] = false,
            [9] = false,
            [10] = true,
            [11] = false,
            [12] = false,
            [13] = true,
            [14] = true,
            [15] = true,
        },
        [15] = {
            [0] = false,
            [1] = false,
            [2] = false,
            [3] = false,
            [4] = false,
            [5] = false,
            [6] = false,
            [7] = false,
            [8] = false,
            [9] = false,
            [10] = false,
            [11] = false,
            [12] = false,
            [13] = false,
            [14] = true,
            [15] = true,
        },
    }
}